### ISSUE TITLE
Missmatches Detector displays irrelevant and nonexistent Segments

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#134]
![image](https://github.com/SebastianHanfland/RallyGPXMerger/assets/43017965/c5f243f2-d7e1-4146-bcbc-b0d32c01f5d2)

**Comment by LeTaPe** [comment]
maybe non-existent because new names of reuploaded segments are not considered

**Comment by SebastianHanfland** [comment]
Hey @LeTaPe,
I find it difficult to reproduce this. Could you please explain a bit more, or show the now tooltip-with-line-breaks?
It looks a bit like an old message, from when the tracks were not yet again construted via "Routen bauen". I do not see another point on how it could have been created like this, because it references old segments which are not anymore within the A9 Route
