### ISSUE TITLE
Visualize Resting Areas and Route Junctions in Map Selectably.

### ISSUE THREAD

**Issue by LeTaPe** [SebastianHanfland/RallyGPXMerger#96]
I want to be able to highlight the resting locations and the intersection points (preferably as enumerated (during hovering) as the entry in the .pdf)

**Comment by SebastianHanfland** [comment]
@LeTaPe 
I am not sure what exactly you want here:
* Is this about the map in the planner or in the version overview?
* Is it just about the highlighting on the map or should it appear in any list?

I think when we need it in the version overview we might need the jsons instead of zips.
When we simply have the routes (in the zips) finding a node point is not trivial because the routes are more or less independent in the version overview

**Comment by LeTaPe** [comment]
Originally the idea was to have it included in both, but now, I believe that enumerating these stops will primarily pose challenges during updating an old version. As long as there is no need from the officials, I'd postpone this issue.
